import { forwardRef } from 'react';
import { imageManifest } from '../data/imageManifest';

/**
 * One <img> that knows about its own derivatives.
 *
 * Give it the source path it always had — `/assets/Autos/IMG_2195.jpg` — and it renders a <picture>
 * that serves WebP to everything that can take it, falls back to the original format, and declares
 * the intrinsic width/height so the layout does not shift as the image arrives.
 *
 * The derivatives and their sizes come from src/data/imageManifest.js, which is generated by
 * `npm run images:optimize`. An image with no manifest entry still renders — it just renders as a
 * plain <img> on the original file, which is what it would have been anyway. That matters: adding
 * an image and forgetting to run the optimizer degrades, it does not break.
 *
 * `sizes` is the one thing worth thinking about per call site. It tells the browser how wide the
 * image will actually be, so it can pick the right candidate before layout exists. Default is
 * 100vw, which is safe (never too small) but downloads more than a grid tile needs.
 *
 * The ref is forwarded to the <img> itself, not the <picture> — Hero.jsx animates that element
 * directly with GSAP.
 */
const Img = forwardRef(function Img({ src, alt, sizes = '100vw', ...rest }, ref) {
    const entry = imageManifest[src];

    if (!entry) {
        return <img ref={ref} src={src} alt={alt} {...rest} />;
    }

    return (
        <picture>
            <source type="image/webp" srcSet={entry.srcset} sizes={sizes} />
            <img
                ref={ref}
                src={entry.fallback}
                width={entry.width}
                height={entry.height}
                alt={alt}
                {...rest}
            />
        </picture>
    );
});

export default Img;
